name: Linters

on: pull_request

jobs:
  base:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - uses: c-hive/gha-yarn-cache@v2
      - name: Install NPM Packages
        run: yarn install
      - name: Review Dog (Standard) 
        run: |
          OUTPUT=$(./node_modules/.bin/ts-standard --report eslint-formatter-rdjson .)
          REPORT=${OUTPUT:-$DEFAULT_REPORT}
          echo "$REPORT" | reviewdog -f=rdjson -reporter=github-pr-review
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_REPORT: >
            {"source":{"name":"eslint","url":"https://eslint.org/"},"diagnostics":[]}

